---
.common:
  image: docker:23
  services:
    - name: docker:23-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      apk add git
      docker buildx create --use
      export $(grep -v '^#' ./VERSION | xargs -0)
    - >
      docker buildx build .
      --platform=linux/arm64,linux/amd64
      --build-arg CADDY_IMAGE_TAG=$CADDY_IMAGE_TAG
      --build-arg CADDY_PLUGIN_TLSCONSUL=$CADDY_PLUGIN_TLSCONSUL
      --build-arg CADDY_PLUGIN_SECURITY=$CADDY_PLUGIN_SECURITY
      --tag $CI_REGISTRY_IMAGE:$DOCKER_VERSION
      --tag $CI_REGISTRY_IMAGE:$DOCKER_MUTABLE_MINOR_VERSION
      --tag $CI_REGISTRY_IMAGE:$DOCKER_MUTABLE_MAJOR_VERSION
      --tag $CI_REGISTRY_IMAGE
      --pull
      --push
  only:
    - master
    - /^stable-.*$/
